# Generated by Django 3.1.3 on 2020-11-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogMain', '0002_auto_20201114_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default='', max_length=500, unique=True),
        ),
    ]
